### ISSUE TITLE
Unable to run 

### ISSUE THREAD

**Issue by abid-khan** [spring-guides/gs-accessing-facebook#14]
I am getting bellow error on context up.

``` java
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.social.facebook.api.Facebook] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1301)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1047)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942)
    at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813)
    at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
```

**Comment by wimdeblauwe** [comment]
Can you compare the code you have with what is in the "complete" directory?

**Comment by kivimango** [comment]
Do not @Inject or @Autowired them.Do as the same in the example: create a constructor with two params Facebook and ConnectionRepository.Guide should mention this, because if you use dependency injection it just wont work.

**Comment by andersonb** [comment]
I'm using the onstructor with two params and having this error.

Parameter 0 of constructor in com.andersonb.HelloController required a bean of type 'org.springframework.social.facebook.api.Facebook' that could not be found.
	- Bean method 'facebook' not loaded because @ConditionalOnWebApplication (required) not a web application

**Comment by gregturn** [comment]
Based on https://spring.io/blog/2018/07/03/spring-social-end-of-life-announcement, this guide is no longer supported.
