### ISSUE TITLE
Null Pointer Exception When Running

### ISSUE THREAD

**Issue by ahmadimt** [spring-guides/gs-accessing-facebook#15]
Hi,

I downloaded this project and I have put my acess key and secret key. When I am running the "complete" project with gradle bootRun, server starts normally. However, when I hit http://localhost:8080/, it throws NullPointerException. Below is the  the error:

java.lang.NullPointerException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy40.isAuthorized(Unknown Source)
	at hello.HelloController.helloFacebook(HelloController.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframeworkrvlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)

**Comment by walery** [comment]
Same here

**Comment by gregturn** [comment]
@habuma Can you take a look?

**Comment by mail82amol** [comment]
It works with spring-boot-starter-parent version 1.2.3.RELEASE . But not with higher versions

**Comment by wimdeblauwe** [comment]
Same problem for me

**Comment by zulfyadhie** [comment]
I managed to solved this issue by following the link below

http://stackoverflow.com/questions/31362619/spring-social-facebook-isauthorized-throws-nullpointerexception

Change the HelloController.java from            
```java
if (!facebook.isAuthorized()) {
   return "redirect:/connect/facebook";
}
```

to
```java
try {
  if (!facebook.isAuthorized()) {
      return "redirect:/connect/facebook";
  }
}catch (NullPointerException e){
      return "redirect:/connect/facebook";
}
```

**Comment by gregturn** [comment]
I'm glad you found a work around. I'm going to leave it up to @habuma if that is the preferred approach for this guide.

**Comment by juplo** [comment]
The workaround perfecly works for me.
Anyway, spring-social-facebook 2.0.3 uses version 2.5 of the graph-api, which does not grant the read_stream permission. Hence, this guide does not work any more.

I would suggest, to ask for "public_profile" and display only profile-data instead of the feed.

By the way, there are two views for the same presented result: src/main/resources/templates/hello.html and src/main/webapp/WEB-INF/views/friends.html the first one is the one which is used and the latter one should be removed, because it usually is the first one, you stumble accross, so anyone will wonder, why changes to that view does not have any effect.

**Comment by juplo** [comment]
Forget about the last part of my comment.
I was mixing up two projects..., sorry!

**Comment by juplo** [comment]
For anybody else, how might stumble accross this, while running the example:
I am writing on a little series of blog articles, that explain the usage of Spring Social.
You can read it on my blog: http://juplo.de/develop-a-facebook-app-with-spring-social-part-00/
It includes a fixed version of the example, which is accessible here: http://juplo.de/git/examples/facebook-app/
(Check out part-00)

**Comment by dsyer** [comment]
the controller implementation has changed and I don't see this error, so I'm going to assume it's fixed

**Comment by lakshmandev** [comment]
I get the same error message when I integrated the code in my already existing spring boot helloworld application created from spring boot web interface. More details [on this link](http://stackoverflow.com/questions/40356261/spring-boot-social-facebook-throws-npe)
